const pastebin = require("pastebin")("2a6b3b82561a00cbeb4a3c6a3d4edce3");

exports.command = {
    action: function(msg,args){
        var logamount = 25;

        if (args = Number(args) && Number(args) > 0){
            logamount = Number(args);
        }

        msg.channel.fetchMessages({limit: logamount})
            .then(msgCollection => {
                var msgs = msgCollection.array();
                console.log(msgs.length);
                var toPrint = "<!DOCTYPE html>\n<html>\n<head>\n<title>#" + msg.channel.name + "'s logs</title>\n<link rel=\"shortcut icon\" href=\"https://110percent.github.io/carameljs/img/favicon.ico\">\n</head>\n<body><link href=\"https://fonts.googleapis.com/css?family=Noto+Sans\" rel=\"stylesheet\"/><style type=\"text/css\">\n* {\nfont-family: \"Noto Sans\", sans-serif;\ndisplay: inline;\nmargin-left: 10px;}\nstyle, head {display:none;}\nbody {\nmargin: 20px;\nbackground:rgba(150,200,255,1)}\n</style>\n<h1>Logs for " + msg.guild.name + " - #" + msg.channel.name + "</h1>\n<br><br><p>Generated by Caramel.js at " + new Date().toUTCString() + "</p>\n<br><br><p>----------------------------------------</p><br><br><br>";
                for (var i = msgs.length - 1; i >= 0; i--){
                    var c = msgs[i]
                    toPrint = toPrint + "<h3>" + c.author.username + "#" + c.author.discriminator + "</h3><span> - " + new Date(c.createdTimestamp).toUTCString() + "</span><br>";
                    console.log(c.content);
                    if (c.content){
                        toPrint = toPrint + "\n<p>" + c.content + "</p>\n";
                    }
                    if (c.attachments.array()[0]){
                        if (["png","jpg","jpeg","webp","gif"].indexOf(c.attachments.array()[0].url.split(".")[c.attachments.array()[0].url.split(".").length - 1]) != -1){
                            toPrint = toPrint + "\n<br><a href=\"" + c.attachments.array()[0].url + "\"><img src=\"" + c.attachments.array()[0].url + "\" height=\"100px\"/></a>\n";
                        }
                        else {
                            toPrint = toPrint + "\n<p>Attachment: <a href=\"" + c.attachments.array()[0].url + "\">" + c.attachments.array()[0].url + "</a></p>";
                        }
                    }
                    toPrint = toPrint + "\n<br><br>\n";
                }
                toPrint = toPrint + "\n<i><p>Caramel.js generated logs here</p></i><br><br><a href=\"https://110percent.github.io/carameljs\"><p>Logs generated by Caramel.js</p></a></body>\n</html>";
                console.log(toPrint);
                msg.channel.sendFile(new Buffer(toPrint,"utf-8"),msg.channel.name + "_logs.html","Here are your logs for the channel!");
            });
    }
}
